# Generated by Django 5.0.3 on 2024-04-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filiere', models.CharField(max_length=100)),
                ('module_fort', models.CharField(max_length=100)),
                ('module_faible', models.CharField(max_length=100)),
            ],
        ),
    ]
