# Generated by Django 5.0.3 on 2024-04-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinput',
            old_name='filiere',
            new_name='Filière',
        ),
        migrations.RenameField(
            model_name='userinput',
            old_name='module_faible',
            new_name='MatièrePref',
        ),
        migrations.RemoveField(
            model_name='userinput',
            name='module_fort',
        ),
    ]
